### ISSUE TITLE
Can't compile?

### ISSUE THREAD

**Issue by keithah** [erikkaashoek/Comskip#24]
Tried compiling comskip on a Ubuntu 14.04.2 system and got an error. Here's the output:

https://gist.github.com/keithah/fd765f12d60b843a875a

Any ideas? Thanks!

**Comment by erikkaashoek** [comment]
Looks like DECLARE_ALIGNED is wrong

2015-09-15 20:17 GMT+02:00 keithah <notifications@github.com>:

**Comment by tmm1** [comment]
DECLARE_ALIGNED comes from avutil (https://github.com/erikkaashoek/Comskip/blob/master/comskip.c#L674), so it seems likely you're using an outdated version of ffmpeg to build.

**Comment by tmm1** [comment]
I've pushed some fixes and confirmed comskip builds on Ubuntu 15.04 with `libavformat-ffmpeg-dev`. The `DECLARE_ALIGNED` error you're seeing is because you're using libav instead of ffmpeg. You may need to compile and install a recent ffmpeg yourself on 14.04.

**Comment by tmm1** [comment]
I've added instructions to the README to compile on ubuntu 14.04

**Comment by keithah** [comment]
thank you!

**Comment by keithah** [comment]
Still getting compile errors:
https://gist.github.com/keithah/a69f8bbd32d813ca9551

Thanks!

**Comment by tmm1** [comment]
Doesn't look like you did a `git pull`

**Comment by tmm1** [comment]
@keithah did you get it working?

**Comment by keithah** [comment]
Yes I did, thanks!
